config/routes.rb
Rails.application.routes.draw do
  resources :event_users
  root 'events#index'
  resources :events
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_users
  has_many :users, through: :event_users
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
has_many :event_users
has_many :events, through: :event_users

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/event_users_controller.rb
class EventUsersController < ApplicationController
  before_action :set_event_user, only: [:show, :edit, :update, :destroy]

  # GET /event_users
  # GET /event_users.json
  def index
    @event_users = EventUser.all
  end

  # GET /event_users/1
  # GET /event_users/1.json
  def show
  end

  # GET /event_users/new
  def new
    @event_user = EventUser.new
  end

  # GET /event_users/1/edit
  def edit
  end

  # POST /event_users
  # POST /event_users.json
  def create
    @event_user = EventUser.new(event_user_params)

    respond_to do |format|
      if @event_user.save
        format.html { redirect_to @event_user, notice: 'Event user was successfully created.' }
        format.json { render :show, status: :created, location: @event_user }
      else
        format.html { render :new }
        format.json { render json: @event_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_users/1
  # PATCH/PUT /event_users/1.json
  def update
    respond_to do |format|
      if @event_user.update(event_user_params)
        format.html { redirect_to @event_user, notice: 'Event user was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_user }
      else
        format.html { render :edit }
        format.json { render json: @event_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_users/1
  # DELETE /event_users/1.json
  def destroy
    @event_user.destroy
    respond_to do |format|
      format.html { redirect_to event_users_url, notice: 'Event user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_user
      @event_user = EventUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_user_params
      params.require(:event_user).permit(:event_id, :user_id, :presence, :organizer)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  # before_action :check_if_admin, only: %i[new edit create update destroy ]
  before_action :check_if_admin, except: %i[index show]
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def check_if_admin
    redirect_to root_path, notice: 'un gros message' unless current_user.admin?
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :content, :scheduled_at, :place)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_users_helper.rb
module EventUsersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/event_users/_form.html.erb
<%= form_for @event_user, :html => { :class => "form-horizontal event_user" } do |f| %>

  <% if @event_user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@event_user.errors.count, "error") %> prohibited this event_user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @event_user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :event_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :event_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:event_id) %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>
  <div class="form-group">
    <%= f.label :presence, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :presence, :class => 'form-control' %>
    </div>
    <%=f.error_span(:presence) %>
  </div>
  <div class="form-group">
    <%= f.label :organizer, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :organizer, :class => 'form-control' %>
    </div>
    <%=f.error_span(:organizer) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                event_users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/event_users/edit.html.erb
<%- model_class = EventUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/event_users/index.html.erb
<%- model_class = EventUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:event_id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:presence) %></th>
      <th><%= model_class.human_attribute_name(:organizer) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @event_users.each do |event_user| %>
      <tr>
        <td><%= link_to event_user.id, event_user_path(event_user) %></td>
        <td><%= event_user.event_id %></td>
        <td><%= event_user.user_id %></td>
        <td><%= event_user.presence %></td>
        <td><%= event_user.organizer %></td>
        <td><%=l event_user.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      event_user_path(event_user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_user_path(event_user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_user_path(event_user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_user_path,
            :class => 'btn btn-primary' %>

app/views/event_users/new.html.erb
<%- model_class = EventUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/event_users/show.html.erb
<%- model_class = EventUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:event_id) %>:</strong></dt>
  <dd><%= @event_user.event_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @event_user.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:presence) %>:</strong></dt>
  <dd><%= @event_user.presence %></dd>
  <dt><strong><%= model_class.human_attribute_name(:organizer) %>:</strong></dt>
  <dd><%= @event_user.organizer %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              event_users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_user_path(@event_user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_user_path(@event_user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => "form-horizontal event" } do |f| %>

  <% if @event.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :content, :class => 'form-control' %>
    </div>
    <%=f.error_span(:content) %>
  </div>
  <div class="form-group">
    <%= f.label :scheduled_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :scheduled_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:scheduled_at) %>
  </div>
  <div class="form-group">
    <%= f.label :place, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :place, :class => 'form-control' %>
    </div>
    <%=f.error_span(:place) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th>Inscrit</th>
      <th><%= model_class.human_attribute_name(:scheduled_at) %></th>
      <th><%= model_class.human_attribute_name(:place) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.id, event_path(event) %></td>
        <td><%= event.title %></td>
        <td><%= event.users.count %></td>
        <td><%= event.scheduled_at %></td>
        <td><%= event.place %></td>
        <td><%=l event.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      event_path(event), :class => 'btn btn-default btn-xs' %>


          <%= link_to 'Je viens', 
                      event_users_path(event_user: {event_id: event,
                                                    user_id: current_user,
                                                    presence: true,
                                                    organizer: false}),
                      method: :post,
                      class: 'btn btn-primary btn-large' %>


          <%- if current_user.admin? %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary'  if current_user.admin? %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @event.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @event.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:scheduled_at) %>:</strong></dt>
  <dd><%= @event.scheduled_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:place) %>:</strong></dt>
  <dd><%= @event.place %></dd>


</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<h2>
  Listes des présents
  <span class="badge"><%= @event.users.count %></span>
  </h2>
<table class='table table-hover'>
<thead>
  <tr>
    <th>Email</th>
    <th>Organisateur</th>
    <th>Listes events du participants </th>
  </tr>
</thead>
<tbody>
<% @event.event_users.each do |eu| %>
<tr>
  <td>
    <%= eu.user.email %>
  </td>
  <td>
    <%= 'x' if eu.organizer %>
  </td>
  <td>
    <%= eu.user %>
  </td>
</tr>
<% end %>
</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MyEventsApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">MyEventsApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "MyEventsApp" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div><!--/row-->

    <footer>
      <p>&copy; Company 2017</p>
    </footer>

  </div> <!-- /container -->

</body>
</html>